# Generated by Django 5.2.8 on 2026-02-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='item_name',
        ),
    ]
