# Generated by Django 5.2.8 on 2026-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
