# Generated by Django 5.2.8 on 2026-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_foodtracking_orderaddress_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
