# Generated by Django 5.2.8 on 2026-03-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0006_cart_added_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='ordet_time',
            new_name='order_time',
        ),
    ]
