# Generated by Django 5.2.13 on 2026-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_rename_ordet_time_orderaddress_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtracking',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
