# Generated by Django 5.2.13 on 2026-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0008_foodtracking_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='foodordering.category'),
        ),
    ]
